server:
  port: 8000

spring:
  application:
    name: msa-gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    gateway:
      routes:
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-server/**
        - id: post-server
          uri: lb://POST-SERVER
          predicates:
            - Path=/post-server/**


#actuator config
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
