server:
  port: 8080

spring:
  application:
    name: demo
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8888/
    use-legacy-processing: true

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: refresh
